plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "echo ${nextRelease.version} > VERSION.txt"
  - "@semantic-release/npm"
  - - "@semantic-release/git"
    - "assets": 
      - "dist/**/*.{js,css}"
      - package.json
      - package-lock.json
      - "CHANGELOG.md"
      "message": |-
        chore(release): ${nextRelease.version} ${nextRelease.notes}  
  - "@semantic-release/github"
branches:
  - "main"
  - "+([0-9])?(.{+([0-9]),x}).x"