name: Release
on:
  push:
    branches:
      - main
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: npm install and build webpack
  #       run: |
  #         npm install
  #     - uses: actions/upload-artifact@main
  #       with:
  #         name: webpack artifacts
  #         path: lib/
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      # - uses: actions/download-artifact@main
      #   with:
      #     name: webpack artifacts
      #     path: public
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm install @semantic-release/github @semantic-release/changelog @semantic-release/git @semantic-release/exec --save-dev
          npx semantic-release          